### ISSUE TITLE
random Segmentation fault during playback on Fedora 20 Gnome

### ISSUE THREAD

**Issue by antokara** [leamas/spotify-make#42]
on Fedora 20 Gnome 64bit - with the latest spotify-make build:

During random playback, mostly after some navigation, it crashes with the following:
~/bin/my-spotify: line 41: 11943 Segmentation fault      (core dumped) LD_LIBRARY_PATH=$( dirname $spotify ) LC_NUMERIC=en_US.utf8 $spotify $@

If I start it again and just resume playback, it will not crash.
However, if I navigate to another artist for example and play, it will probably crash after like 10 seconds or so.

It was not like that, this started the last couple of days, perhaps a system package update causes it?

**Comment by JeremieRapin** [comment]
Hum, same here:
```
[0303/133717:FATAL:main_delegate.cc(449)] Check failed: !loaded_locale.empty(). Locale could not be found for en-US
/usr/bin/spotify: line 36: 23279 Aborted                 (core dumped) LD_LIBRARY_PATH=$( dirname $spotify ) LC_NUMERIC=en_US.utf8 $spotify $@
```

**Comment by ScottyTM** [comment]
according to https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Spotify-0-9-11-for-GNU-Linux/m-p/1031732/highlight/true#M109783 this is caused by gtk+-2.24.26 a downgrade to gtk+-2.24.25-r1 resolves this.

Also Spotify 1.0.1 beta is available:
https://twitter.com/felipernb/status/575669571044114432

**Comment by antokara** [comment]
Just found this bug report of the gnome regression and its stated as fixed 2 weeks ago:
https://bugzilla.gnome.org/show_bug.cgi?id=745536

**Comment by antokara** [comment]
Performed a system/gtk update recently and it appears fixed. will reopen if problem reappears.
