### ISSUE TITLE
spotify-client_0.9.17.1.g9b85d43.7-1_amd64.deb

### ISSUE THREAD

**Issue by martinr63** [leamas/spotify-make#43]
the data file has changed. It is now data.tar.xz
So I get:
```
tar xzf data.tar.gz
tar (child): data.tar.gz: Funktion open fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by leamas** [comment]
Which means there is a new release:  spotify-client-qt_0.9.17.1.g9b85d43.7

Thanks for heads-up! As usual, a new release means some work; this process is far from streamlined. Stay tuned...

**Comment by leamas** [comment]
The unpacking work, so this bug could be closed, sort of. However, there are dependency problem which needs to be sorted out with the new version before it can be really useful. Leaving bug open
